### PR TITLE
Fwd port fix improve MCQ/MRQ choice HTML (OC-514)

### PR DESCRIPTION
**Pull request by bradenmacdonald**
This is a forward port of OC-89 / https://github.com/edx-solutions/xblock-mentoring/pull/98 to mentoring v2.
### Before screenshot:

before1

and 

before2
### After screenshot:

after

Note: I changed the `vertical-align` from `middle` to top. I think it looks better. Here's an example of the vertical-align middle before I changed it to top:
vertical-align-middle

### CODE REVIEW

**Comment by e-kolpakov** [comment]
@bradenmacdonald looks good, except that for some reason it still renders on new line when editing MCQ:

mcq-inner

Also, it does not apply styling to choices when selecting correct ones:

mcq-editor

So, :+1: conditional these two issues are addressed somehow.

**Comment by bradenmacdonald** [comment]
@e-kolpakov Thanks for the review.

I fixed the first issue you found.

For the second one, it cannot be fixed in this PR, so I am merging this PR now. A fix for that issue is at https://github.com/edx/xblock-utils/pull/14 but as you'll see, I think it might be better not to allow HTML in the Studio edit dialog.

**Comment by antoviaque** [comment]
@bradenmacdonald We can't merge the forward-port PRs now I'm afraid - this would require another OSPR review to allow to include it on edx.org. :/ Can you rewind master to the version from the review in https://github.com/open-craft/xblock-mentoring/pull/4 (you will need to alter the history, not just revert the changes, so that it doesn't appear in the history when we send the PR to update the requirement on edx/edx-platform). Instead, I would merge the new changes in another branch, where we'll put the changes until the review process for edx.org is over.

CC'ing @mtyaka so he doesn't rebase/merge https://github.com/open-craft/xblock-mentoring/pull/9 before this is done.

**Comment by bradenmacdonald** [comment]
@antoviaque Oh, okay. No problem. I have reset master to the reviewed version and merged all the forward ports onto a new branch called `develop`.

**Comment by antoviaque** [comment]
@bradenmacdonald Perfect - thank you! : )

**Pull request merged**
